services:
  ray-head:
    build: .
    container_name: ray-head-dev
    command: >
      ray start --head
        --dashboard-host=0.0.0.0
        --port=6379
        --dashboard-port=8265
        --temp-dir=/tmp/ray
        --block
    ports:
      - "6379:6379"    # Ray client
      - "8265:8265"    # Ray Dashboard + Jobs REST API
      - "8080:8080"    # Ray metrics
      - "10001:10001"  # Ray client/worker RPC
    volumes:
      - ./:/app
    tmpfs:
      - /tmp/ray:rw,noexec,nosuid,size=1g
    environment:
      - RAY_ADDRESS=auto
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    healthcheck:
      test: ["CMD-SHELL", "ray status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  vllm:
    build: .
    container_name: vllm-dev
    depends_on:
      ray-head:
        condition: service_healthy
    ports:
      - "8000:8000"    # vLLM API
    volumes:
      - ./:/app
    environment:
      - RAY_ADDRESS=ray://ray-head:10001
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    command: >
      python -m vllm.entrypoints.openai.api_server
        --model microsoft/DialoGPT-medium
        --host 0.0.0.0
        --port 8000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports: 
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    depends_on:
      - ray-head
      - vllm

  loki:
    image: grafana/loki:latest
    container_name: loki-dev
    ports: 
      - "3100:3100"
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail-dev
    volumes:
      - /var/log:/var/log:ro
      - ./monitoring/promtail/config.yaml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dev
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki

volumes:
  ray-data:
    driver: local
  prometheus-data:
    driver: local
  loki-data:
    driver: local
  grafana-data:
    driver: local
